import "server-only";

import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "pdf-lib";

export type InvoicePdfItem = {
  name: string;
  variant?: string;
  quantity: number;
  unitPrice: number;
  total: number;
};

export type InvoicePdfInput = {
  invoiceNumber: string;
  orderId?: string;
  awb?: string;
  customerName: string;
  customerPhone?: string;
  customerEmail?: string;
  address?: string;
  items: InvoicePdfItem[];
  subtotal: number;
  discount?: number;
  tax: number;
  deliveryFee?: number;
  total: number;
  createdAt: string;
};

function money(value: number): string {
  return `INR ${Number(value || 0).toFixed(2)}`;
}

export async function generateInvoicePdf(
  input: InvoicePdfInput,
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const page = pdf.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();
  const margin = 45;
  let y = height - margin;

  const drawText = (
    text: string,
    x: number,
    yPos: number,
    size = 10,
    font = regular,
  ) => {
    page.drawText(String(text ?? "").slice(0, 90), {
      x,
      y: yPos,
      size,
      font,
      color: rgb(0.12, 0.15, 0.2),
    });
  };

  const drawLine = (yPos: number) => {
    page.drawLine({
      start: { x: margin, y: yPos },
      end: { x: width - margin, y: yPos },
      thickness: 0.7,
      color: rgb(0.82, 0.84, 0.88),
    });
  };

  drawText("Sreshta Logistics + Sreshta Foods", margin, y, 16, bold);
  drawText("INVOICE", width - 120, y, 16, bold);
  y -= 28;

  drawText(`Invoice No: ${input.invoiceNumber}`, margin, y, 10, bold);
  drawText(
    `Date: ${new Date(input.createdAt).toLocaleDateString("en-IN")}`,
    width - 160,
    y,
    10,
  );
  y -= 18;

  if (input.awb) {
    drawText(`AWB: ${input.awb}`, margin, y, 10);
    y -= 16;
  }
  if (input.orderId) {
    drawText(`Order ID: ${input.orderId}`, margin, y, 10);
    y -= 16;
  }

  y -= 8;
  drawText("Bill To", margin, y, 11, bold);
  y -= 16;
  drawText(input.customerName || "Customer", margin, y, 10);
  y -= 14;
  if (input.customerPhone) {
    drawText(`Phone: ${input.customerPhone}`, margin, y, 9);
    y -= 13;
  }
  if (input.customerEmail) {
    drawText(`Email: ${input.customerEmail}`, margin, y, 9);
    y -= 13;
  }
  if (input.address) {
    drawText(input.address, margin, y, 9);
    y -= 13;
  }

  y -= 10;
  drawLine(y);
  y -= 22;

  // table header
  page.drawRectangle({
    x: margin,
    y: y - 6,
    width: width - margin * 2,
    height: 22,
    color: rgb(0.94, 0.95, 0.97),
  });
  drawText("Item", margin + 4, y, 9, bold);
  drawText("Qty", 320, y, 9, bold);
  drawText("Rate", 380, y, 9, bold);
  drawText("Amount", 470, y, 9, bold);
  y -= 26;

  for (const item of input.items ?? []) {
    if (y < 140) break;
    const label = item.variant
      ? `${item.name} (${item.variant})`
      : item.name;
    drawText(label, margin + 4, y, 9);
    drawText(String(item.quantity ?? 0), 320, y, 9);
    drawText(money(item.unitPrice), 380, y, 9);
    drawText(money(item.total), 470, y, 9);
    y -= 20;
  }

  drawLine(y);
  y -= 24;

  const right = width - 90;
  const labelX = width - 200;

  drawText("Subtotal", labelX, y, 9);
  drawText(money(input.subtotal), right, y, 9);
  y -= 16;

  if ((input.discount ?? 0) > 0) {
    drawText("Discount", labelX, y, 9);
    drawText(`- ${money(input.discount ?? 0)}`, right - 8, y, 9);
    y -= 16;
  }

  if ((input.deliveryFee ?? 0) > 0) {
    drawText("Delivery", labelX, y, 9);
    drawText(money(input.deliveryFee ?? 0), right, y, 9);
    y -= 16;
  }

  drawText("Tax", labelX, y, 9);
  drawText(money(input.tax), right, y, 9);
  y -= 20;

  page.drawRectangle({
    x: labelX - 10,
    y: y - 6,
    width: 165,
    height: 26,
    color: rgb(0.94, 0.95, 0.97),
  });
  drawText("TOTAL", labelX, y, 11, bold);
  drawText(money(input.total), right - 10, y, 11, bold);

  drawText(
    "Generated by Sreshta Logistics + Sreshta Foods",
    margin,
    40,
    8,
  );

  return pdf.save();
}
